### ISSUE TITLE
Incorrect Case when Changing from Uppercase to Titlecase

### ISSUE THREAD

**Issue by dylan-k** [Benature/obsidian-text-format#12]
If you select a string in UPPERCASE and do the "convert to title case" you get unusual results. What I do to get around this is to first convert to all lowercase, and then it will change to title case from there, as expected.

**Comment by Benature** [comment]
What is the unusual result? Can you give a sample? Here is my test
![image](https://user-images.githubusercontent.com/35028647/146485563-a355c6c6-3e36-4adb-bed0-f5b562acb8a8.png)
