### ISSUE TITLE
Blank lines not cleared if there's any white space

### ISSUE THREAD

**Issue by willdhorn** [Benature/obsidian-text-format#16]
For some reason, when I paste code from certain places into Obsidian, it will insert blank lines between each line. However, the lines added are not completely blank, but instead have white space characters that match the indent of the pasted code.

For example, if I copied the following code:
```
function foo() {
    bar();
}
```
and pasted it into obsidian, it would turn into:
```
function foo() {
<\t>
    bar();
<\t>
}
```
(side note: in my notes I see spaces instead of tabs as my settings are configured to replace/convert tabs, but it shouldn't really make a difference)

Unfortunately, when I run the command to remove blank lines, nothing happens because (as the readme implies) the command is simply replacing '\n\n' with '\n'. 

If the command were changed to use an expression like '\n<whitespace>\n'  then it would be able to handle cases like this.

**Comment by willdhorn** [comment]
Just played around with a regex tester and I think the line at https://github.com/Benature/obsidian-text-format/blob/cf2062ac01b4a08b841e56b8e0dba81e817f31a2/main.ts#L229 :
```
 replacedText = selectedText.replace(/\n+/g, "\n");
```
should be replaced with:
```
replacedText = selectedText.replace(/\n\s*\n/g, "\n");
```

**Comment by Benature** [comment]
Nice, modified in v1.6.2
