### ISSUE TITLE
Mobile Support?

### ISSUE THREAD

**Issue by jeffvogelsang** [Benature/obsidian-text-format#19]
Can this plugin be updated to support mobile devices?

**Comment by Benature** [comment]
I would like to, but I don't know how to modify to support mobile.😥

**Comment by Benature** [comment]
Thanks to https://keathmilligan.net/obsidian-plugin-cross-platform-testing, now I know one of the problems is about the [RegExp](https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group)

```
[error] Plugin failure: obsidian-text-format SyntaxError: Invalid regular expression: invalid group specifier name
```

(fixing on it)

**Comment by Benature** [comment]
v2.0.0 support mobile, finally!
