### ISSUE TITLE
Remove /n but not /n/n

### ISSUE THREAD

**Issue by eleanorkonik** [Benature/obsidian-text-format#2]
It would be helpful for preserving the formatting of a PDF if I could go assign all of the actual paragraph breaks with two newlines, and then this plugin could remove all single-breaks but not the actual paragraph breaks. ❤️

**Comment by Benature** [comment]
Thank you for your suggestion, it is very practical and useful. Please update to v0.2.2 so the plugin support ignoring multi \n.

But there is a question left, what should we do with, say, `\n\n\n`, should we replace it with `\n\n`? If yes, should it be the part of `newline` command or make it a new command? For me, I do not encounter such a condition, for now, so I would like to see if someone needs this feature then decide whether to implement it.

**Comment by Benature** [comment]
After committing the new version, I suddenly think that the name of command `newline` is not accurate now, which is not "Remove all newline characters in selection" anymore. I am considering "Merge broken paragraph(s) in selection", what do you think about it? I will update the command name in the next version, afraid that some users get used to type "newline" to search this command, (me, for example).

**Comment by eleanorkonik** [comment]
I've updated, thank you! 

I think "merge broken paragraphs in selection" is more descriptive. 

For my usecase, \n\n\n\n --> \n\n would be very useful, and I would be fine with it being all part of the same default behavior.

**Comment by Benature** [comment]
👌  I've updated the command name.

As for the redundant newline characters, I add a setting for it so that users can decide whether remove them or not.

**Comment by eleanorkonik** [comment]
Thank you so much this is very exciting!!
