### ISSUE TITLE
Remove redundant spces not working on Windows 7

### ISSUE THREAD

**Issue by drpalli** [Benature/obsidian-text-format#21]
Hi,
After selecting the text in editor view in Obsidian, Pressing command+P and selecting redundant spaces doesn't delete the extra spaces. I am using the latest version of Obsidian.

https://user-images.githubusercontent.com/67685865/158059684-4cd2405c-fc9d-472b-b910-3634ea0902ba.mp4

**Comment by drpalli** [comment]
Was using the wrong command. Everything works fine

**Comment by Benature** [comment]
Could you please give a sample text for me to test?

btw, you said the latest version, is it v0.13.33?

**Comment by Benature** [comment]
> Was using the wrong command. Everything works fine
