### ISSUE TITLE
Feature Request - Remove junk Characters from Text

### ISSUE THREAD

**Issue by looneyapache** [Benature/obsidian-text-format#23]
Hi,

Your plugin works great!

Any possibility we could have a feature where in it removed junk characters from paragraph/pasted text, just leaving "."/periods where they are.

Thank you!

**Comment by Benature** [comment]
Sorry, I don't quite understand what junk characters are. Can you give an example, like input is blablabla and expected output(result) is blablabla.

**Comment by looneyapache** [comment]
Sure please,

Following is input text"

The quick *~~~Brown f%%ox jumps) right~ over$ the lazy! dog).

Expected output (Clean) : 

The quick brown fox jumps right over the lazy dog.

**Comment by looneyapache** [comment]
It typically happens when I use OCR for old documents (hand typed documents)  or corrupted PDF's or Old dbase/Foxpro Memo files (corrupted). I think its mainly because old documents are yellow and smudgy and are hard to scan where OCR inserts characters on its own :)

**Comment by looneyapache** [comment]
Here is one example I picked from Google, Some documents have close resemblance to example :
![bitonal-doc](https://user-images.githubusercontent.com/10562851/162892214-b052f6fc-c2f1-4114-8cd7-e8373fbf7299.png)
)

**Comment by Benature** [comment]
The pictures you provide are illegible even by myself, what is the copy text like? My OCR result is below

```txt
The preser.t rerort is Oric of 玉 numbr wiich dr：prr4lrex duri上i anJ 1945 fpr the Frreign poncnic 永ministration Lmembevs:st t.

the unitedi St:tes Tarift' Cornissint:. Orine to the desire of thr 我 、” Econoniy Aininistration to obt ir this matcri.1. !.xs prompt1y as pces1.o, the reports yere Yot revievvd by the Trri:: Connissien. A11 st:tenont.s o1 fagt or opinion in tese renorts CI &ttributithlp t； the. irciyilei Etaef nembers tho prraredi th.em. Th.:Y. 1l，洲以：rieinlt：itsed f conf idential u: of Goverrnent xgencivs, ut .•r（〉 noR brin.: Hdpnniis with the consent oi the For(imr. Eocnnic iuiri:.istrtior:.
```

If the copy text is similar to this, I don't think directly deleting junk characters can get the expected text.

**Comment by looneyapache** [comment]
Thank you for responding! :)

I am noobie and I posted same issue on Obsidian forum, requesting for help. ( https://forum.obsidian.md/t/replace-all-asterisks-in-a-given-file/35238/25?u=looney.apache )

Solution was not as elegant as yours - But it works for me (at least for now )  

I paste my text to be scrubbed in to  https://textcleaner.net/ and get back cleaned text as need be.

I value your assistance. Thank you!

**Comment by looneyapache** [comment]
True!
Also , I've been using "Obsidian Text Format" and I've discovered that it's fantastic at fixing broken paragraphs.

Unquestionably one of the GOOD plugins.
