### ISSUE TITLE
Capitalize sentence doesn't work for bullet lists

### ISSUE THREAD

**Issue by coltborg** [Benature/obsidian-text-format#25]
When trying to capitalize a selected sentence, it will not capitalize the first letter in unordered lists. It will capitalize the first letter of ordered lists however:

https://user-images.githubusercontent.com/9101728/168122876-5c919fee-5497-4579-96ba-ba9fa024aaae.mp4

**Comment by AMGMNPLK** [comment]
It doesn't work in regular text, at least for me. The lowercase formatting works perfectly, but uppercase doesn't.
