### ISSUE TITLE
Capitalize sentence issue with contractions.  

### ISSUE THREAD

**Issue by thecookiemomma** [Benature/obsidian-text-format#27]
**Current Behavior**:  When I use the "Capitalize the first word in every sentence in selection" in a paragraph of text, it also capitalizes the first letter after the apostrophe in a contraction. For example, I get `don'T` and `you'Re`

**Expected Behavior**:  When I use the function, it should ignore the letters inside a word, with or without apostrophes inside it, such as `don't` and `you're`

I do appreciate this plugin a lot. Thank you.

**Comment by Benature** [comment]
I will detect `ve|t|m|d|ll|s|re`, if I miss some cases, plz remind me.
