### ISSUE TITLE
Format Action: Combo of multi format function

### ISSUE THREAD

**Issue by Benature** [Benature/obsidian-text-format#29]
This should be custom, users can self-config at setting.

e.g. `replace ligature` + `convert url links to wikilink` + `lowercase` + `capitalize only first word of sentence`

**Comment by ryanwwest** [comment]
I like this too. I often paste in some text paragraphs that get three spaces, so I end up first using the command to remove newlines, then the command to add just 1 newline after each paragraph, and finally I use the (non-plugin) command `Toggle blockquote`. 

However, this makes me wonder if there's another plugin that already allows you to create such combos that could be used to create a new command for calling _any_ sequence of commands.

**Comment by icytree** [comment]
> However, this makes me wonder if there's another plugin that already allows you to create such combos that could be used to create a new command for calling _any_ sequence of commands.

Take a look at the [QuickAdd plugin](https://github.com/chhoumann/quickadd) it can allow you to combine Obsidian commands as macros and then executing them using either the command palette, a little custom pop up menu or a hotkey. Its great !
