### ISSUE TITLE
Capitalise just the first letter of a list item/sentence

### ISSUE THREAD

**Issue by NB574** [Benature/obsidian-text-format#3]
Is it possible to add a funtion to capitalise just the first letter of a list item/sentence? I love this addon, it's just one of those QOL ones which makes everything so much easier, if you're editing things.

**Comment by Benature** [comment]
support it on version 1.1.0.

I only consider the conditions that the letter is after `?!.` or the letter is the first of the line and selection. If there are some conditions that I miss, please comment here, and I will update the code.

**Comment by NB574** [comment]
Oh wow that's great, that should work brilliantly, looking forward to it, thank you!
