### ISSUE TITLE
Contextual menu Font color

### ISSUE THREAD

**Issue by lveillard** [Benature/obsidian-text-format#30]
Hello ! Nice plug in ;)

any idea to make this work with a contextual menu (right click) + color changer?

Both current solutions:
```
<span class="purple"> This note will be purple </span>
```

and 

\``` note-purple
This text will be pruple
\```

Are not amazing because they add a lot of noise in edit version. 

It would be amazing to be have somethig like Highlightr , where you see the color also in editor mode

**Comment by Benature** [comment]
There's already an issue about context menu #26

**Comment by Benature** [comment]
As for font color, I will not recommend doing so, because I think it contradicts the Markdown design philosophy.

But if you insist, you can config in wrapper setting by yourself.

![image](https://user-images.githubusercontent.com/35028647/187136894-08b0c577-bf7d-4b86-889e-6f139ea6b6a7.png)


The sample setting is
```
purple-span
<span style="color:purple;">
</span>

**Comment by lveillard** [comment]
I guess I'm a tradition breaker 😂 

Thank you very much for the example, is EXACTLY what I wanted. I saw the wrapper function, but it was not clear to me how to use it.

**Comment by yarub123** [comment]
So after adding the wrapper like is shown above how then do we go about using it?

I select the word, then toggle the option of "comment" from text format in command palette...

but it does not make it Purple...it just adds the prefix and suffix. 

Ofc it's supposed to add the prefix and suffix, it's just doing it's job. But I'm not seeing any color...

Apologies if this is already been answered before.

**Comment by Benature** [comment]
In my Ob, it's purple.
<img width="575" alt="image" src="https://user-images.githubusercontent.com/35028647/234755519-c302fe91-53e3-4216-88fc-9cc38cae33b9.png">

maybe you need to check your theme or custom css files.

**Comment by yarub123** [comment]
@Benature Awesome got it to work. The last code was fucked up. 

I had it the prefix written as: <span class="purple">
