### ISSUE TITLE
The command `Capitalize all words in selected text` requires the selected text to be in lower case.

### ISSUE THREAD

**Issue by nhan000** [Benature/obsidian-text-format#31]
I want to turn "THIS PHRASE" into "This Phrase", but the command `Capitalize all words in selected text` does nothing.
 
I need to turn the text into lower case first before applying the command `Capitalize all words in selected text`.

**Comment by Benature** [comment]
It can be config in setting 
![image](https://user-images.githubusercontent.com/35028647/188359073-50987a72-fdbb-4155-b659-b6dddeb06a73.png)
