### ISSUE TITLE
How to add \n into wrapper prefix and suffix?

### ISSUE THREAD

**Issue by PGTKi** [Benature/obsidian-text-format#36]
Thanks for this fantastic plugin. I want to user the custome wrapper feature to code-format my plain text, but i found the prefix and suffix in the setting menu can just be filled with one-line text, right? So the effect of adding ``` before the text selected isn't as expected. Is there any simple way to do this?
![image](https://user-images.githubusercontent.com/38714936/200261589-2ca607ca-8559-4ed5-b2ff-e1afd7ec12c2.png)

**Comment by Benature** [comment]
Please try it in version 1.8.5

**Comment by PGTKi** [comment]
> Please try it in version 1.8.5

It works now!! Thanks a lot ~
