### ISSUE TITLE
Feature: organize to-do lists

### ISSUE THREAD

**Issue by enzon19** [Benature/obsidian-text-format#37]
Sort by completion/check. Transform this type of to-do list:
```
- [ ] Eat
- [x] Shower
- [ ] Market
- [x] Soccer
```
Into that:
```
- [x] Shower
- [x] Soccer
- [ ] Eat
- [ ] Market
```
Or that:
```
- [ ] Eat
- [ ] Market
- [x] Shower
- [x] Soccer
```
If this feature doesn't match the plugin theme, but someone know another plugin that can do that, please, let me know!

**Comment by Benature** [comment]
This feature would be handy for me I think :) Before that I just moved lines with shortcuts manually.

v1.9.0 has supported this feature, please take a test. Feel free to reopen this issue if you find any bugs of it or have other suggestions.

**Comment by enzon19** [comment]
Perfect! Working perfectly, thanks! I love when we have devs that support suggestions from the users! Thanks again
