### ISSUE TITLE
Merge broken paragraphs- separate bullets= separate paragraphs?

### ISSUE THREAD

**Issue by Tom233-ai** [Benature/obsidian-text-format#39]
Is there any way to use the merge broken paragraphs function for a document containing many bullet points and have each bullet point be treated as its own paragraph? Currently I am converting them 1 by 1 which takes a while. 

Thanks!

**Comment by Benature** [comment]
Could you give a simple sample of the document?

Maybe you can use `Format bullet list` command after `Merge broken paragraphs`🤔

**Comment by Tom233-ai** [comment]
Thanks for the speedy reply. I actually thought of that. When I merge broken paragraphs, it still keeps the - before each bullet point but when I format bullet list the formatting doesn't change at all? It doesn't separate them back into bullets. Maybe user error? I have tried it on a few created documents and have the same issue. 

- Walk the
dog
- Go to the
movies
- Train the 
dolphins

After merge broken paragraphs (works great)
- Walk the dog - Go to the movies - Train the dolphins

After format bullet list
- Walk the dog - Go to the movies - Train the dolphins

**Comment by Tom233-ai** [comment]
I see the problem actually by taking another look at the readme example. For the command to register there needs to be a • in between, a "-" won't work.

- • first, blahblah • second, blahblah • third, blahblah

**Comment by Benature** [comment]
![image](https://user-images.githubusercontent.com/35028647/212611097-460b8d45-096a-4094-9f00-a8fa5376c47a.png)

You can add `-` in the setting, as the figure is shown above.

**Comment by Tom233-ai** [comment]
Thank you so much. Your plugin will save me hours of tidying up highlighted notes from pdfs. Appreciate the help
