### ISSUE TITLE
Remove wikilinks format in selection does not handle alternative text

### ISSUE THREAD

**Issue by nickynicolson** [Benature/obsidian-text-format#41]
**Background**
The internal link format supports using a different caption for the link, using the syntax:
```[[Internally linked page|custom display caption]]```
See the [Change the link display text](https://help.obsidian.md/Linking+notes+and+files/Internal+links#Change+the+link+display+text) section of the Obsidian help page on internal links.

**Expected behaviour** of **Remove wikilinks format in selection** command: all parts of the link would be removed including the page title, leaving only the alternate text 
Before: ```Here is my linked text paragraph which has a [[Internally linked page|custom display caption]]```
After: ```Here is my linked text paragraph which has a custom display caption```

**Actual behaviour**: only the square brackets are removed, the page title is left in the text.

Before: ```Here is my linked text paragraph which has a [[Internally linked page|custom display caption]]```
After:  ```Here is my linked text paragraph which has a Internally linked page|custom display caption```

**Comment by Benature** [comment]
👍 Thanks so much
