### ISSUE TITLE
Plugin not working in Canvas card?

### ISSUE THREAD

**Issue by e-pet** [Benature/obsidian-text-format#43]
What the title says... I have a block of text. I can format it when pasting it in a normal Obsidian note, but not when I paste it in a card in a Canvas. Not sure if this is a general Obsidian problem or something related to this plugin?

**Comment by kzha0** [comment]
Any updates on this issue? I was using the plugin today and was wondering why the text format plugin wasn't working. Turns out there's an issue with canvas files.

**Comment by Benature** [comment]
The first time I encountered this issue I didn't know how to solve it. Just now I found a reference and knew how to fix it. The new version should work as expected. Feel free to re-open this issue if something's wrong.

**Comment by ShahriarKh** [comment]
Seems like it's still broken 👀
Obsidian: 1.5.3
Text Format: 2.5.0

**Comment by Benature** [comment]
Hi @ShahriarKh, which commands failed?

**Comment by ShahriarKh** [comment]
Hi @Benature 
I think all of them. Convert to uppercase, convert to lowercase, custom formats, ...
It works correctly in notes, but not in canvas cards.

**Comment by ShahriarKh** [comment]
Nevermind, I uninstalled the plugin and installed again and the problem is solved. 👍🏽
