### ISSUE TITLE
Feature requests - custom small and big words on Title Case

### ISSUE THREAD

**Issue by denizido** [Benature/obsidian-text-format#44]
Hi, first congratulations on this great plugin, it's really useful for me.

My feature request is to be able to add custom small words to be lowercase when I apply the Title Case command.

The plugins works lowering the English small words, but my first language is not English, so it doesn't fully work for me.

I tried modifying the js file and add my custom words and it works, but is not as easy and I'll loose it when the plugin gets updated.

Also, if possible, it would also help to have some custom words/acronyms that would be UPPERCASE  when Title Case was applied.

Thanks in advance.

**Comment by Benature** [comment]
Hi, can you give some examples of your requests?

btw, as you have tried modified the js file and success, it is recommended to make a PR or post your modified js content in this issue.

**Comment by Benature** [comment]
The setting `Proper noun` may be the feature that you want. 

If you have any questions, feel free to re-open this issue. :)

**Comment by denizido** [comment]
Hello, sorry to revive old thread.


Actually, I had two requests on my post.

The "Proper noun" setting solves the latter part of the request.

But the first part of my feature request would be to add "small word", similar to proper nouns.

I'll explain.

When I use the Title Case command, on an English sentence, it returns something like this:

> The Cat Sat on the mat.

Here, the words "on" and "the" are all lowercase, .

But it only works with English sentences.

So my request is to add a setting (similiar to "proper noun"), so the user can add small words on other languages.
