### ISSUE TITLE
Sort To-Do List combines two different lists if they're separated only by one blank line, and doesn't sort them.

### ISSUE THREAD

**Issue by YousufSSyed** [Benature/obsidian-text-format#46]
Let's say I have a list like this:
```
- [x] asdsds
- [ ] asdasdsa
- [ ] asdasd

- [x] asdasdsad
- [ ] sdsdf
- [ ] asdasd
```
If I run the command with the cursor on the bottom of the first list, on the blank line, or on the 1st line of the 2nd list, then it will sort each list and remove the blank line, combining them but not sorting the new combined list.

If there's two separate lines, then it will sort both lists without combing them, which is also not ideal. It should only work on the list where the caret is.

**Comment by Benature** [comment]
Before the feature is supported, you can select the area by hand as an workaround.

**Comment by Benature** [comment]
Here is the new design, which will be released in later beta version

Whole file:

```md
Lalalala
- [ ] Todo a
- [x] Todo bb
- [ ] Todo ccc
Aaaaaa
- [ ] Todo 1
- [x] Todo 22
- [ ] Todo 333
Bbbbbb
```
## Cases without selection
### Case 1
When the caret is out of the todo block, sort all todo blocks. 
For example, the caret is at line 
```
Bbbbbb
```

Result:
```md
Lalalala
- [ ] Todo a
- [ ] Todo ccc
- [x] Todo bb
Aaaaaa
- [ ] Todo 1
- [ ] Todo 333
- [x] Todo 22
Bbbbbb
```

### Case 2
When the caret is in one todo block, just sort this todo block

For example, the caret is on line
```
- [ ] Todo ccc
```

Result:

```md
Lalalala
- [ ] Todo a
- [ ] Todo ccc
- [x] Todo bb
Aaaaaa
- [ ] Todo 1
- [x] Todo 22
- [ ] Todo 333
Bbbbbb
```

## Cases with selection
### case 3

When the selection is in one line, the same result with case 1.

For example, I select `do 1` in 
```
- [ ] Todo 1
```

Result:
```
Lalalala
- [ ] Todo a
- [ ] Todo ccc
- [x] Todo bb
Aaaaaa
- [ ] Todo 1
- [ ] Todo 333
- [x] Todo 22
Bbbbbb
```

### case 4

When the selection crosses lines, only sort the todo lines in selection

1. For example, I select

```md
- [ ] Todo a
- [x] Todo bb
- [ ] Todo ccc
Aaaaaa
- [ ] Todo 1
```

Result:
```
Lalalala
- [ ] Todo a
- [ ] Todo ccc
- [x] Todo bb
Aaaaaa
- [ ] Todo 1
- [x] Todo 22
- [ ] Todo 333
Bbbbbb
```

2. For example, I select
```md
- [ ] Todo 1
- [x] Todo 22
```

Result
```md
Lalalala
- [ ] Todo a
- [x] Todo bb
- [ ] Todo ccc
Aaaaaa
- [ ] Todo 1
- [x] Todo 22
- [ ] Todo 333
Bbbbbb
```
