### ISSUE TITLE
Feature request: Sort bullet list

### ISSUE THREAD

**Issue by juanbretti** [Benature/obsidian-text-format#47]
I would be nice to have the ability to sort a list or multiple text lines.
From:

```
- a
- c
- b
```

into:
```
- a
- b
- c
```

and alternate into:
```
- c
- b
- a
```

As **text lines**.
From:

```
a
c
b
```

into:
```
a
b
c
```

and alternate into:
```
c
b
a
```

Thank you.

**Comment by juanbretti** [comment]
Maybe, you could consider merging -with the proper authorization- the development by @Vinzent03 at https://github.com/Vinzent03/obsidian-sort-and-permute-lines

**Comment by Benature** [comment]
> Maybe, you could consider merging -with the proper authorization- the development by @Vinzent03 at https://github.com/Vinzent03/obsidian-sort-and-permute-lines

If the plugin you mentioned meet your needs, it is suggested that installing both two plugins, which is most convenient.
