### ISSUE TITLE
Doesn't work right with multiple text selections

### ISSUE THREAD

**Issue by joem** [Benature/obsidian-text-format#48]
I was attempting to uppercase text in a few different places, so I made multiple selections (by holding Option while selecting additional things) and I invoked Text Format: Uppercase Selected Text via the command palette. Instead of correctly uppercasing everything, it uppercased the last selection and then replaced all previous selections with the uppercased last selection.

I'm using Version 1.1.16 (Installer 1.0.0) of Obsidian and version 2.2.1 of Text Format. Let me know if you need any more details/info. I tried it a few times in a few documents and it seems to work consistently like that for me.

I glanced through the open and closed issues and didn't see any mention of this, but maybe it was phrased a way I wasn't looking for, so if this is a duplicate issue, sorry about that.

(I've been using this plugin for a while and really love this plugin. Even without working right on multiple selections, it's still such a useful plugin! Thanks!)

**Comment by joem** [comment]
Oops, forgot to mention I have version 2.2.1 of Text Format installed.

**Comment by erroreyes** [comment]
It would be great for this to be possible. I installed the plugin specifically to perform case changes for multiple selections and lines.

**Comment by Benature** [comment]
That is a good suggestion. However, I do not know how to get the multi-selection via the Ob's API. In my tests, method `.getSelection()` can only get the first selection, but all multi-selections are replaced with the formatted result of the first selection.

**Comment by erroreyes** [comment]
I don't know the API at all, but I took a quick look and there seems to be an [`Editor.getRange()`](https://docs.obsidian.md/Reference/TypeScript+API/Editor/getRange) method that makes me wonder if that would help in achieving this.

**Comment by Benature** [comment]
Sorry that I did not reply this issue in time.

`getRange(from, to)` is useful to get the text from the specific range. However, I need to get the cursor's position at the first. In my test, `editor.getCursor()` can only get the first position even though I've set several cursors.

```ts
    console.log(
      editor.getCursor("from"),
      editor.getCursor("to"),
      editor.getCursor("head"),
      editor.getCursor("anchor"),
      editor.getSelection(),
    )
```

<img width="1179" alt="image" src="https://github.com/Benature/obsidian-text-format/assets/35028647/03f40614-ae3f-417d-b2af-a15d93a97028">

I'm eager to implement this feature as well. But for now, Obsidian's multi-cursor/selection behaviour is still not as good as other ide, like vscode. 😢

**Comment by Benature** [comment]
Good news, I just read the api again, found `listSelections`. It works! Now I can get the positions of multi-cursor. :)

**Comment by Benature** [comment]
To support multi-cursor, refactoring the code is needed. I've just made the basic refactoring. I beta pre-release `3.0.0-b1` is just released. Anybody who is interested is welcome to install the beta version and test it! 

I expect these commands should work well:
```
"lowercase"
"uppercase"
"capitalize-word"
"capitalize-sentence"
"titlecase"
"togglecase"
```

Other commands may have a wrong selection at last. Please tell me if you find something wrong!

---

To install the beta version, you can install it by BRAT (https://github.com/TfTHacker/obsidian42-brat), and check if it is a beta version.

**Comment by erroreyes** [comment]
v3.0.0-b1 seems to be working well so far. I'll be using it all day today at work and see if anything strange happens.

Thank you for finding the time to fix this!

**Comment by Benature** [comment]
v3.0.0 is released finally. Feel free to re-open this issue if something is wrong :)
