### ISSUE TITLE
Togglecase not working as expected

### ISSUE THREAD

**Issue by rbanks88** [Benature/obsidian-text-format#49]
When I select text and invoke the Togglecase command, it changes the text case, then deselects and leaves the cursor at the end of the what I’d selected. So I have to reselect the text and invoke again to toggle the next case.

My only cases in the list are set to:
lowerCase
upperCase

So, it seems it should just toggle the selected case back and forth between upper- and lower-case.

If the text is uppercase, it converts to lowercase.
If the text is lowercase, it converts to uppercase.

If the selected text contains a word that has both upper- and lower-case letters (such as a capitalized word), nothing happens.

Any ideas?

Obsidian 1.2.8
Text Format 2.2.1

Thanks,
Russell

**Comment by Benature** [comment]
Hi, this issue should be fix in v2.2.2. Feel free to reopen this issue if you have any question.
