### ISSUE TITLE
Extend the plugin functionality to other cases

### ISSUE THREAD

**Issue by EhuddR** [Benature/obsidian-text-format#5]
Hi, I would like to know if there is a possibility to add this case to the plugin:

If a word has one or more letters inside the word in Uppercase.

```diff
- HEllo 
+ Hello
+ hello
+ HELLO
```

**Comment by Benature** [comment]
Hi, you can lowercase the word at first and then uppercase of title case it.

**Comment by EhuddR** [comment]
Yes, but it is really annoying to do so over and over again. If you could fix that it will be nice. Thanks anyway for the amazing plugin.

**Comment by EhuddR** [comment]
Thank you very much. It's amazing now.
