### ISSUE TITLE
Error: Remove URL links format in selection

### ISSUE THREAD

**Issue by kin30528** [Benature/obsidian-text-format#50]
The "Remove URL links format in selection" function does not work properly，The URL cannot become  https://doi.org/10.1016/s0005-7967(01)00098-5. The additional number "**00098-5)**" at the end of the URL，Please see the picture for details, Thx：

## Before
![image](https://github.com/Benature/obsidian-text-format/assets/121107652/83559d6b-acc8-42d4-939e-41e5e289e260)

## After
![image](https://github.com/Benature/obsidian-text-format/assets/121107652/f7fc0847-c9c5-44d7-ae1c-c9e0e3823e10)

**Comment by Benature** [comment]
Hi, this issue should be fix in v2.2.2. Feel free to reopen this issue if you have any question.
