### ISSUE TITLE
Plugin Setting "Remove redundant blank lines" not behaving as expected

### ISSUE THREAD

**Issue by chrisweis** [Benature/obsidian-text-format#54]
Hi,

Awesome plugin, loving it!  I'm struggling with one behavior.  When I enable this "Remove redundant blank lines" radio button...
![image](https://github.com/Benature/obsidian-text-format/assets/13931731/47d7b1ec-601a-48d3-a920-1b41a321876a)

...I expect that this markdown...
```
Text A

Text B


Text C
```

...will be converted to this markdown...
```
Text A

Text B

Text C
```

...but instead it is converted to this:
```
Text A
Text B
Text C
```

Am I missing something or misunderstanding how that feature should work?

Thanks!
Chris

**Comment by Benature** [comment]
Hi, the setting is for the command `Merge broken paragraphs(s) in selection`, which behave as 
```
Text A

Text B

Text C
```
