### ISSUE TITLE
Remove URL Links does not work as expected

### ISSUE THREAD

**Issue by thisisclement** [Benature/obsidian-text-format#56]
Hi there, I downloaded this plugin (version 2.2.5) so that I can remove the links in my text. 
Example:
`[Pricing](https://k21academy.com/amazon-web-services/aws-lake-formation/#6)`
Using "remove URL links" it becomes:
`https://k21academy.com/amazon-web-services/aws-lake-formation/#6`

I am expecting `Pricing` which was what I understood as functionality from this plugin. 

I'll be happy to provide any further info as well. Thanks.

**Comment by thisisclement** [comment]
Hi Benature, 
I believe for me coming from any text formatter (MS Docs, or Notion), is to remove the link to the text. i.e to remove the url under the text, (Pricing), and just leave Pricing as the final text. Hope that clarifies.

**Comment by Benature** [comment]
In v2.2.6, I add a setting for `Remove URL Links`. In your case, you can modify the format in the setting to be `{text}`, so that you can maintain the text rather than the url.

**Comment by Benature** [comment]
I think this issue is addressed, feel free to reopen this issue if have any question.
