### ISSUE TITLE
The selected Uppercase text cannot change

### ISSUE THREAD

**Issue by kin30528** [Benature/obsidian-text-format#59]
I find that all capitalized articles cannot be changed into "Capitalize all words in selected text" or "Capitalize only first word of sentence in selected text". but Other functions work fine.

Thanks for the plugin, it saves me a lot of time!

**Comment by Benature** [comment]
Hi, can you provide some sample that the plugin failed to convert what you are expected?

btw, I found #65 is kinda similar to your issue. Do you have the same problem? There is a sample in that issue.

**Comment by kin30528** [comment]
> 您好，您能否提供一些範例，說明該外掛未能轉換您所期望的內容？
> 
> 順便說一句，我發現#65與你的問題有點相似。你有同樣的問題嗎？該期有一個樣本。


Thx, I used three examples, and tried to change them to capitalize only the first word of sentence, but only one of the examples was successfully changed.

## Not working
In The Eye Of The Beholder: Individual Differences In Perceived Social Isolation Predict Regional Brain Activation To Social Stimuli.

IN THE EYE OF THE BEHOLDER: INDIVIDUAL DIFFERENCES IN PERCEIVED SOCIAL ISOLATION PREDICT REGIONAL BRAIN ACTIVATION TO SOCIAL STIMULI.

## Working
in the eye of the beholder: individual differences in perceived social isolation predict regional brain activation to social stimuli.

**Comment by Benature** [comment]
旧版本中这个设置默认为「关」，需要手动开启一下
<img width="793" alt="image" src="https://github.com/Benature/obsidian-text-format/assets/35028647/2e852221-f19a-4a85-aa4e-b59dcc9c3e10">

same as https://github.com/Benature/obsidian-text-format/issues/31#issuecomment-1236522954

**Comment by kin30528** [comment]
> 舊版本中這個設定默認為「關」，需要手動開啟一下 <img alt="image" width="793" src="https://user-images.githubusercontent.com/35028647/275236763-2e852221-f19a-4a85-aa4e-b59dcc9c3e10.png">
> 
> same as [#31 (comment)](https://github.com/Benature/obsidian-text-format/issues/31#issuecomment-1236522954)
可以了，謝謝😊
