### ISSUE TITLE
Remove Hyphens feature kills extra characters.

### ISSUE THREAD

**Issue by goncharovdk** [Benature/obsidian-text-format#60]
The current implementation of this feature kills the character before the hyphen. E.g. "si- mply" -> "smply".

Proposed solution: The code
``` js
case "hyphen":
        replacedText = selectedText.replace(/(\w)-[ ]/g, "");
```
should replace with "$1", not with an empty string.

``` js
> "si- mply".replace(/(\w)-[ ]/g, "")
'smply'
> "si- mply".replace(/(\w)-[ ]/g, "$1")
'simply'
```

P.S. Created this issue as there was no reply to my comment to the original (closed) issue #15.

**Comment by Benature** [comment]
Thanks for your suggestion! And sorry that I missed reading your comment in the closed issue. The code is updated in v2.2.8. Feel free to re-open this issue if this feature does not work well. :)
