### ISSUE TITLE
Feature request: Trim trailing spaces

### ISSUE THREAD

**Issue by goncharovdk** [Benature/obsidian-text-format#61]
Please add the possibility of removing trailing spaces from lines. (This is not the same as "Remove all spaces" or "Remove redundant spaces".)  Many users are asking for this feature, see e.g. https://forum.obsidian.md/t/trim-trailing-whitespace/17047

**Comment by Benature** [comment]
v2.6.0 has supportted this feature, please have a try! 

Free feel to reopen this issue if something is wrong.

**Comment by Benature** [comment]
As this feature is quite simple, it will be moved to "Custom replacement" (#77) after v3.0.0. User who has similar demand can refer to this setting. Any other use cases are welcome to share!

<img width="619" alt="image" src="https://github.com/Benature/obsidian-text-format/assets/35028647/0ed6032d-a470-4682-acaf-e02b1c3af873">

- name: `Remove trailing spaces`
- search: `(\s*)(?=\n)|(\s*)$`
- replace: ``

**Comment by goncharovdk** [comment]
Found a GUI issue: when a new empty custom replacement is added with [+] button, the "Custom replacement [v]" immediately collapses into "Custom replacement [^]"  and visually disappears.
