### ISSUE TITLE
Title case won't work if the text in is uppercase.

### ISSUE THREAD

**Issue by albertoloscerritos** [Benature/obsidian-text-format#65]
Lest say I want to convert

THIS SENTENCE
to
This Sentence

If the text is in uppercase, selecting Title case won't do anything.

Thanks

**Comment by albertoloscerritos** [comment]
I also tried using: 
- Capitalize all words in selected text
- Capitalize only first word of sentence in selected text 

None of them worked when the text is in uppercase.

**Comment by Benature** [comment]
Hi, can you provide the version you are using?

Here are my tests under v2.2.8

```md
THIS SENTENCE
`Title case`:
This Sentence
`Capitalize all words in selected text`:
This Sentence
`Capitalize only first word of sentence in selected text`:
This sentence
```

**Comment by albertoloscerritos** [comment]
I'm using obsidian 1.4.13. 
Text Format 2.2.8
All snippets are disabled.
Here is a GIF showing the current behavior.
 
![TEXT FORMAT BUG](https://github.com/Benature/obsidian-text-format/assets/16707033/5ef3789c-4d5d-4810-b922-ed837f51473f)

**Comment by Benature** [comment]
Thats weird, can you check the console, if there are some outputs

**Comment by nhan000** [comment]
@albertoloscerritos try this setting here https://github.com/Benature/obsidian-text-format/issues/31

**Comment by Benature** [comment]
> @albertoloscerritos try this setting here #31

Maybe I should set this setting default as ON? 🤔️
