### ISSUE TITLE
Lowercase/Uppercase inline note title

### ISSUE THREAD

**Issue by totholz5d** [Benature/obsidian-text-format#68]
Hi there,

Would it be technically possible to make the Lowercase and Uppercase commands also active on the inline title?

At the moment I copy paste the title in the note body, apply the case modification command and then  paste the result back in the inline title... it works but it would be amazing to be able to do this directly in the inline title box!

**Comment by Benature** [comment]
Hi, v2.7.0 finally supports modification of inline title, including commands:
```
lowercase
uppercase
capitalize-word
capitalize-sentence
titlecase
togglecase
```

Please have a try. Feel free to re-open this issue if something is wrong.
