### ISSUE TITLE
Remove URL not working, inserting wrong SPACE char

### ISSUE THREAD

**Issue by schobernoise** [Benature/obsidian-text-format#72]
I just came across this behaviour (first time user of your plugin):

I copied some text off of a wikipedia page, selected the whole paragraph and ran the command "Remove URL links format in selection". Nothing happened.
So I pressed "Convert all links to Wikilinks, which worked well. Then I pressed "Remove all Wikilinks from selection", which also worked - but I noticed, that the Paragraph was broken up like this:

![image](https://github.com/Benature/obsidian-text-format/assets/58608284/3ab63f73-963c-4596-9349-c4a06289fb13)

I investigated and found out that all of a sudden the spaces where not spaces anymore, but NO-BREAK SPACEs. So this whole bunch of words got treated like one long goddamn word.

![image](https://github.com/Benature/obsidian-text-format/assets/58608284/a5ae1922-bfdf-4236-9462-20b994e85337)

I ain't no technician but that seems to me like some technical problem has had happened, sir.

Broken down in issues, this would be:
- "Remove URL links format in selection" is not working
- "Remove all Wikilinks from selection" inserted fake space characters.

Hope this helps!

**Comment by Benature** [comment]
Hi, can you paste the original text here? This will help me reproduce your issue and debug it when I have some free time.

**Comment by schobernoise** [comment]
Of course! It was the second paragraph here: https://de.wikipedia.org/wiki/Oberkreide

`Der Name Kreide wurde 1822 durch den belgischen Geologen [Jean Baptiste Julien d’Omalius d’Halloy](https://www.wikiwand.com/de/Jean_Baptiste_Julien_d%E2%80%99Omalius_d%E2%80%99Halloy) nach den stark [Calciumcarbonat](https://www.wikiwand.com/de/Calciumcarbonat)-haltigen Fossilien von [Krebstieren](https://www.wikiwand.com/de/Krebstiere), [Korallen](https://www.wikiwand.com/de/Korallen), [Muscheln](https://www.wikiwand.com/de/Muscheln), [Schnecken](https://www.wikiwand.com/de/Schnecken) und [Einzellern](https://www.wikiwand.com/de/Einzeller), die in den Gesteinen dieses Systems vorkommen, benannt. Das eher landläufig „[Kreide](https://www.wikiwand.com/de/Kreide_(Gestein))“ genannte Gestein ist eine spezielle Form von [Kalkstein](https://www.wikiwand.com/de/Kalkstein). Allerdings können Sedimentgesteine der Kreidezeit aus völlig anderen Mineralen aufgebaut sein, wie beispielsweise die überwiegend aus Quarzkörnern bestehenden und häufig vorkommenden „Kreidesandsteine“, deren Bezeichnung ausschließlich auf ihre Entstehungszeit hinweist.`

**Comment by Benature** [comment]
Hi, I've modified my code, is the text below what you expect? If yes, I may update the code in the next version.

`Der Name Kreide wurde 1822 durch den belgischen Geologen Jean Baptiste Julien d’Omalius d’Halloy nach den stark Calciumcarbonat-haltigen Fossilien von Krebstieren, Korallen, Muscheln, Schnecken und Einzellern, die in den Gesteinen dieses Systems vorkommen, benannt. Das eher landläufig „Kreide“ genannte Gestein ist eine spezielle Form von Kalkstein. Allerdings können Sedimentgesteine der Kreidezeit aus völlig anderen Mineralen aufgebaut sein, wie beispielsweise die überwiegend aus Quarzkörnern bestehenden und häufig vorkommenden „Kreidesandsteine“, deren Bezeichnung ausschließlich auf ihre Entstehungszeit hinweist.`

**Comment by schobernoise** [comment]
Yes, this is absolutely correct - Space Characters are SPACE and not NONBREAK-SPACE.
