### ISSUE TITLE
[FR] Split paragraph into sentences

### ISSUE THREAD

**Issue by VerAn1015** [Benature/obsidian-text-format#78]
Currently, we can merge broken paragraph in selection. There should also be an opposite of it wherein we break the paragraph into sentences. I believe this would be useful as well when copying and pasting information from pdfs and instead of it being a block of text, the sentences in the paragraph are broken up into its own line.

**Comment by Benature** [comment]
That's true. But what criteria can I rely on to determine the appropriate places for paragraph breaks?

**Comment by VerAn1015** [comment]
Perhaps adopting an approach similar to [Semantic Line Breaker plugin](https://github.com/chrisgrieser/obsidian-sembr?tab=readme-ov-file#what-are-semantic-line-breaks)? But instead of it also breaking compound sentences separated by a comma, it would only break paragraphs into sentences that are in "full stop" indicated by a period.

**Comment by VerAn1015** [comment]
That is correct. For reference, this is the [online tool](https://sentencesplitter.com/) I currently use for such functionality. It would be great if the plugin does it within Obsidian. Thanks!

**Comment by Benature** [comment]
To boost the process of solving issues, I've developed a feature for custom replacement. Here is the solution for your issue with the custom replacement:
<img width="793" alt="image" src="https://github.com/Benature/obsidian-text-format/assets/35028647/b7f6be48-6899-478a-940f-950954b4a7d9">

Here are the contents of the screenshot above
```
Split paragraph into sentences
([\.\!\?]\s+)
$1\n
```

(note that the plugin version should be over v2.7.1)

**Comment by VerAn1015** [comment]
Just tested and it's perfect! Thank you!

**Comment by pablo-hp** [comment]
I was trying with:
. 
.\n\n
And it wasn't working.

Test with:
([\.\!\?]\s+)
$1\n\n
And now it's working exactly the way I wanted.

Thanks.
