### ISSUE TITLE
Add Extra Line Break to Paragraphs

### ISSUE THREAD

**Issue by eleanorkonik** [Benature/obsidian-text-format#8]
I know I can do this with Notepad++ but it occurred to me that this might be within scope for this plugin, so I thought I'd file the issue:

I have a bunch of old stories that I wrote in different programs and come in formatted like this: 

![image](https://user-images.githubusercontent.com/75856959/139584804-ff92f1f6-9384-4216-97ef-6e05096169e2.png)

and it would be handy if I could put them into the more markdown/computer friendly version where there's double-spacing between paragraphs. I've been doing it by hand 🙈

**Comment by eleanorkonik** [comment]
![text-format-linebreak](https://user-images.githubusercontent.com/75856959/149357626-1aae9f43-5262-4505-a905-3195849a22b7.gif)

Am I doing something wrong? 🤔

**Comment by Benature** [comment]
I am not sure that am I get your point correctly, do you mean add double space `  ` after all paragraphs?

**Comment by eleanorkonik** [comment]
I think so. The idea is to turn

`this paragraph
and this paragraph`

Into

`this paragraph

and this paragraph`

**Comment by Benature** [comment]
aha, I miss-understand to add double space 🤣

**Comment by Benature** [comment]
select the paragraphs or select all by ⌘/ctrl+A, then run the command in v1.5.2

**Comment by eleanorkonik** [comment]
Ohhhhh _that's_ what you meant by "after." 😅 

YES! It works, thank you so much ❤️

**Comment by Benature** [comment]
As this feature is quite simple, it will be moved to "Custom replacement" (#77) after v3.0.0. The user who has similar demands can refer to this setting. Any other use cases are welcome to share!

<img width="605" alt="image" src="https://github.com/Benature/obsidian-text-format/assets/35028647/51ebbfcf-aa3f-428f-bb62-0ca688f3d278">

- name: `Add extra line break between paragraphs`
- search: `\n`
- replace: `\n\n`
