### ISSUE TITLE
iOS: failed to load plugin error when trying to enable Text format

### ISSUE THREAD

**Issue by VKondakoff** [Benature/obsidian-text-format#82]
Hello!

I’m receiving `failed to load plugin` error when trying to enable Text format 2.7.0 on iPadOS 15.8.2:

![B5F29523-8170-47CC-B13C-5E1B0F2437FF](https://github.com/Benature/obsidian-text-format/assets/230824/106b5995-9d47-4c82-b185-19ec5bd1b907)

It's interesting, that I don’t see the same error on iOS 17.4:

![154A1EC1-341A-4505-9000-2B07F334859B](https://github.com/Benature/obsidian-text-format/assets/230824/07f1cdb3-3823-4550-97a6-207e18156262)

Any ideas what may be wrong? Thanks!

**Comment by Benature** [comment]
Hi, that's quite weird. I don't have any idea what's wrong for now. 

You may re-install the plugin and try again. Note that before you uninstall the plugin, it would be better to copy plugin's `data.json` (`.obsidian/plugins/obsidian-text-format/data.json`) file so that you can recover your custom setting.

If the bug persists: As I'm not with my iPad recently, you may follow the guide below to get the console log in mobile if you have time.
1. Install https://github.com/KjellConnelly/obsidian-dev-tools by BRAT (https://github.com/TfTHacker/obsidian42-brat)
<img width="797" alt="image" src="https://github.com/Benature/obsidian-text-format/assets/35028647/db75fc37-3ed7-4f98-8d44-f4c2226a8a71">

2. Toggl console with command palate in iPad (I can only get a screenshot of mobile with iPhone for now)
![image](https://github.com/Benature/obsidian-text-format/assets/35028647/16cb9030-ecbc-4439-aff1-eda4ad981611)

3. Try enable Text Format and get the error console log

**Comment by VKondakoff** [comment]
Reinstalling Text Format, reloading Obsidian and restarting iPad does not solves the issue: I'm still receiving `failed to load plugin` when trying to enable Text Format. Will try to get the console log on mobile and write back.

Until then, [here is what I have found](https://forum.obsidian.md/t/ios-bug-plugins-main-js-contains-regex-regex-which-is-lookbehind-will-cause-load-plugin-failed/46636/1). Any chance this may be the reason of the `failed to load plugin` error?

**Comment by Benature** [comment]
> Until then, [here is what I have found](https://forum.obsidian.md/t/ios-bug-plugins-main-js-contains-regex-regex-which-is-lookbehind-will-cause-load-plugin-failed/46636/1). Any chance this may be the reason of the `failed to load plugin` error?

It had been a problem before. But this problem should affect all mobiles including iPhone. So I think this time it may be not about the regex problem.

**Comment by Benature** [comment]
What's the version of Obsidian? (iPad and iPhone)

**Comment by VKondakoff** [comment]
Latest insider build: 1.5.11 (133) - sorry for not mentioning this in the initial report.

**Comment by VKondakoff** [comment]
Here is what I see on Console when trying to enable TF: 

![IMG_0772](https://github.com/Benature/obsidian-text-format/assets/230824/d3f24ea0-461f-4765-a9c8-74dc297302bd)

**Comment by Benature** [comment]
😢 Oh no, I cannot get the information I want in the plugin's console. But I found another plugin that can write console output in a file. I'm going to try both two plugins to get the console log for debugging when I get back my iPad, though its iPadOS version is different from yours.

Here is the guide to another plugin. If you are interested and have free time, it is welcome that you test it on your iPad. Sorry about the failure of the first plugin's debugging, it must have wasted your time.

---

Plugin https://github.com/velebit/obsidian-save-console-log is more similar to the debugging method when I solved https://github.com/Benature/obsidian-text-format/issues/19#issuecomment-1340552188 in my memory (The link in the quote is not available now, so I could not find back the debug script at first🤦).

- Install save-console-log by BRAT with fix version `0.1.2`. *(Directly installing by BRAT is buggy, I've make a PR about it)*
- Try to enable Text Format on the iPad. This plugin should write all console output to a file. https://github.com/velebit/obsidian-save-console-log/blob/main/src/obsidian-debug-mobile.ts#L21-L25
- Get the output txt from `.obsidian/plugins/obsidian-save-console-log/logs.txt`

**Comment by VKondakoff** [comment]
That's it! 

> [error] Plugin failure: obsidian-text-format SyntaxError: Invalid regular expression: invalid group specifier name

**Comment by Benature** [comment]
Sorry, I made a wrong judgment. As I don't have much free time today, I made a quick fix to remove `(?<=)` and released a new beta version (3.0.0-b2). I have not tested all commands yet, so it may be buggy. You can install the beta version by BRAT, hope it will work on your iPad. If the beta version has something wrong, please tell me.

**Comment by VKondakoff** [comment]
Yes, 3.0.0-b2 build works well on my iPad. Many of the Text Format commands (for example remove Internal links or URLs are non available, though).

**Comment by Benature** [comment]
I've finally got back my iPad and found it works well with v2.7.1. So your inference is correct -- your iPad version is too low to support the regex. I've added a `try...catch` to try to avoid this compatible issue in the later version.

The latest beta version is 3.0.0-b5 now. The BRAT will update beta plugins every time you open Obsidian by default. The command "remove URL links" should work well now. If you find any commands don't work correctly, please just tell me. The official version will be released this week, I suppose.

**Comment by VKondakoff** [comment]
Thank you! TF 3.0.0-b5 loads well on my iPad and everything seems to work.
