### ISSUE TITLE
"Uppercase to capitalize word" not working

### ISSUE THREAD

**Issue by zhaoruibing** [Benature/obsidian-text-format#9]
Despite the change made in #5 #6, "Uppercase to capitalize word" is not working still.
My guess is, perhaps, there is a typo in the code.

The typo is in [main.ts line 129](https://github.com/Benature/obsidian-text-format/blob/7f15d479d52524b62404e0671e04f91e30712259/main.ts#L129)

Shouldn't this
```javascript
        if (this.settings.LowercaseFirst) {
          replacedText = selectedText.toLowerCase();
        } else {
          replacedText = selectedText;
        }
```

Be this
```javascript
        if (this.settings.LowercaseFirst) {
          selectedText = selectedText.toLowerCase();
        } else {
          selectedText = selectedText;
        }
```
Note the change from `replacedText` to `selectedText`.

If the above change is made, line 184 also needs to be changed.

**Comment by Benature** [comment]
thank you 👍

**Comment by zhaoruibing** [comment]
NP. Thank you for making this plugin, saved me tons of time~
