### ISSUE TITLE
[Bug] slugify removes swedish characters

### ISSUE THREAD

**Issue by matsarvendal** [Benature/obsidian-text-format#94]
**Problem Description**: 
When using the function “Text Format: Slugify selected text (‘-‘ for space)” on a text containing swedish characters, these characters are removed.

**How to reproduce the problem**:

Input:
```md
testing swedish characters åäö testing
```

Result:
```md
testing-swedish-characters-testing
```

Expected:
```md
testing-swedish-characters-åäö-testing
```

**Environment**
- Obsidian version: 1.5.12 (134)
- Text Format version: 3.0.1
- Platform: iOS

**Comment by Benature** [comment]
`slugify` command is a PR #57 by @izikeros . Thanks for him again.

In his code, accents and diacritics are removed.
```ts
// Remove Accents and Diacritics
text = text.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
```

After I preserved Swedish characters, the result of your example is 
```md
testing-swedish-characters-aao-testing
```

Note that it is `aao` but not `åäö`.

I'm not sure if it satisfies your demand? As in his description of PR #57 :

>The slugify function will convert a string into a URL-friendly format, removing special characters, converting to lowercase, replacing spaces with dashes, removing accents and diacritics, and handling numerals and hyphens. This utility is helpful in generating slugs for URLs or filenames from a given text, making the text more SEO-friendly and easier to manage.

**Comment by matsarvendal** [comment]
That’s OK, thanks!

/Mats
mats
